importation des bibliothèques nécessaires et chargement de fichier à etudier

In [11]:
import os 
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import datetime
base='..\\data\\nettoyer\\Online_Retail_a_analyser.csv'
df_a_analyser= pd.read_csv(base,parse_dates=['InvoiceDate'])
df_a_analyser['InvoiceDate']=df_a_analyser['InvoiceDate'].dt.normalize()

détermination de la date de la dernière commande

In [12]:
date_max= df_a_analyser['InvoiceDate'].max() +pd.Timedelta(days=1)

creation du data_frame score R:Recency F :Frequency M:Monetary

In [14]:
rfm = df_a_analyser.groupby('Customer ID').agg({
'InvoiceDate': lambda x: (date_max- x.max()).days,
'Invoice': 'nunique',
'Revenue': 'sum'
}).reset_index()         
rfm.rename(columns={'InvoiceDate':'Recency','Invoice':'Frequency','Revenue':'Monetary'}, inplace=True)
print(rfm.head(20))

    Customer ID  Recency  Frequency  Monetary
0       12346.0      326          7  77442.96
1       12347.0        3          8   4921.53
2       12348.0       76          5   2019.40
3       12349.0       19          4   4428.69
4       12350.0      311          1    334.40
5       12351.0      376          1    300.93
6       12352.0       37         10   2849.84
7       12353.0      205          2    406.76
8       12354.0      233          1   1079.40
9       12355.0      215          2    947.61
10      12356.0       23          6   6371.73
11      12357.0       34          3  18287.66
12      12358.0        2          4   2457.24
13      12359.0       58          8   8034.50
14      12360.0       53          8   4252.89
15      12361.0      288          4    511.25
16      12362.0        4         10   5226.23
17      12363.0      110          2    552.00
18      12364.0        8          4   1313.10
19      12365.0      292          2    641.38

La segmentation RFM repose sur l'attribution de scores selons trois critères:
-La Récence : où un score élevé valorise la proximité temporelle du dernière achat.
-La Fréquence:récompensant le nombre élevé de transactions.
-Le Montant :distinguant les clients ayant généré le chiffre d'affaire le lus conséquent.

In [4]:
rfm['R_Score'] = pd.qcut(rfm['Recency'], 5, labels=[5, 4, 3, 2, 1], duplicates='drop')  


rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 5, labels=[1, 2, 3, 4, 5], duplicates='drop')
rfm['M_Score'] = pd.qcut(rfm['Monetary'].rank(method='first'), 5, labels=[1, 2, 3, 4, 5], duplicates='drop')

affichage du score sous forme de caratère string (lettres)

In [5]:
rfm['RFM_Score'] = rfm['R_Score'].astype(str) + \
                      rfm['F_Score'].astype(str) + \
                      rfm['M_Score'].astype(str)

print(rfm[['Customer ID','RFM_Score']].head().to_string(index=False))
rfm['R_Score']=rfm['R_Score'].astype(str)
rfm['F_Score']=rfm['F_Score'].astype(str)
rfm['M_Score']=rfm['M_Score'].astype(str)

 Customer ID RFM_Score
     12346.0       245
     12347.0       545
     12348.0       344
     12349.0       535
     12350.0       212

Dfinir les conditions de la  segmentation finale

In [6]:
conditions = [
    # Champions : Récence élevée (4 ou 5) ET Fréquence/Montant élevés (4 ou 5)
    (rfm['R_Score'].isin(['4', '5'])) & (rfm['F_Score'].isin(['4', '5'])) & (rfm['M_Score'].isin(['4', '5'])),
    # Clients Fidèles : Récence moyenne (2 ou 3) ET Fréquence/Montant élevés (4 ou 5)
    (rfm['R_Score'].isin(['2', '3','4'])) & (rfm['F_Score'].isin(['3','4', '5'])),
    # Clients En Danger : Récence faible (1 ou 2) mais historiquement bons (F & M élevés)
    (rfm['R_Score'].isin(['1', '2'])) & (rfm['F_Score'].isin(['4', '5'])),
    # Clients Perdus : Tout est faible
    (rfm['R_Score'].isin(['1', '2'])) & (rfm['F_Score'].isin(['1', '2'])),
    (rfm['R_Score'].isin(['4', '5'])) & (rfm['F_Score'].isin(['1']))
]

choix_segments = [
    'Meilleurs Clients (Champions)',
    'Clients Fidèles',
    'Clients En Danger',
    'Clients Perdus',
    'Nouveau client'
]
# 6. Application des règles (le reste est classé 'Autres')
rfm['Segment'] = np.select(conditions, choix_segments, default='Autres')
rfm

,Customer ID,Recency,Frequency,Monetary,R_Score,F_Score,M_Score,RFM_Score,Segment
0,12346.0,326,7,77442.96,2,4,5,245,Clients Fidèles
1,12347.0,2,8,4921.53,5,4,5,545,Meilleurs Clients (Champions)
2,12348.0,75,5,2019.40,3,4,4,344,Clients Fidèles
3,12349.0,19,4,4428.69,5,3,5,535,Autres
4,12350.0,310,1,334.40,2,1,2,212,Clients Perdus
...,...,...,...,...,...,...,...,...,...
5787,18283.0,4,22,2664.90,5,5,4,554,Meilleurs Clients (Champions)
5788,18284.0,432,1,461.68,1,2,2,122,Clients Perdus
5789,18285.0,661,1,427.00,1,2,2,122,Clients Perdus
5790,18286.0,477,1,833.48,1,2,3,123,Clients Perdus
5791,18287.0,43,7,4182.99,4,4,5,445,Meilleurs Clients (Champions)

In [7]:

pourcentage=rfm.groupby(['Segment']).size().reset_index(name='nombre')
somme=pourcentage['nombre'].sum()
somme
pourcentage['pourcent']=((pourcentage['nombre']/somme)*100 ).map('{:.2f}%'.format)  # afficher deux chiffres apres
pourcentage

                         Segment  nombre pourcent
0                         Autres    1116   19.27%
1              Clients En Danger      81    1.40%
2                Clients Fidèles    1659   28.64%
3                 Clients Perdus    1501   25.92%
4  Meilleurs Clients (Champions)    1268   21.89%
5                 Nouveau client     167    2.88%

calcule revenue par segment